package greenwolf13.magecraft;

import greenwolf13.magecraft.*;
import net.minecraft.src.Block;
import net.minecraft.src.CraftingManager;
import net.minecraft.src.CreativeTabs;
import net.minecraft.src.Item;
import net.minecraft.src.ItemStack;
import net.minecraft.src.Material;
import net.minecraftforge.common.ForgeHooks;
import net.minecraftforge.common.MinecraftForge;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Init;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.Mod.PostInit;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;

@Mod(modid="MageCraftCore", name="MageCraft", version="Alpha 0.1.0")
@NetworkMod(clientSideRequired=true, serverSideRequired=false)
public class MageCraft {
   public final static Item itemEssenceMageCraft = new MageCraftItem(26201, 64, CreativeTabs.tabMisc, 1, "itemEssenceMageCraft");
   public final static Item itemEssence2MageCraft = new MageCraftItem(26202, 64, CreativeTabs.tabMisc, 1, "itemEssence2MageCraft");
   public final static Item itemEssence3MageCraft = new MageCraftItem(26203, 64, CreativeTabs.tabMisc, 1, "itemEssence3MageCraft");
   public final static Item itemLeadIngotMageCraft = new MageCraftItem(26204, 64, CreativeTabs.tabMisc, 1, "itemLeadIngotMageCraft");
   public final static Item itemSilverIngotMageCraft = new MageCraftItem(26205, 64, CreativeTabs.tabMisc, 1, "itemSilverIngotMageCraft");
   public final static Item itemMithrilIngotMageCraft = new MageCraftItem(26206, 64, CreativeTabs.tabMisc, 1, "itemMithrilIngotMageCraft");
   public final static Item itemAdamantIngotMageCraft = new MageCraftItem(26207, 64, CreativeTabs.tabMisc, 1, "itemAdamantIngotMageCraft");
   public final static Item itemElectrumIngotMageCraft = new MageCraftItem(26208, 64, CreativeTabs.tabMisc, 1, "itemElectrumIngotMageCraft");
   public final static Item itemSaltpeterMageCraft = new MageCraftItem(26209, 64, CreativeTabs.tabMisc, 1, "itemSaltpeterMageCraft");
   public final static Item itemSulphurMageCraft = new MageCraftItem(26210, 64, CreativeTabs.tabMisc, 1, "itemSulphurMageCraft");
   public final static Item itemApatiteMageCraft = new MageCraftItem(26211, 64, CreativeTabs.tabMisc, 1, "itemApatiteMageCraft");
   public final static Item itemOnyxMageCraft = new MageCraftItem(26212, 64, CreativeTabs.tabMisc, 1, "itemOnyxMageCraft");
   public final static Item itemRubyMageCraft = new MageCraftItem(26213, 64, CreativeTabs.tabMisc, 1, "itemRubyMageCraft");
   public final static Item itemSapphireMageCraft = new MageCraftItem(26214, 64, CreativeTabs.tabMisc, 1, "itemSapphireMageCraft");
   public final static Item itemQuartzMageCraft = new MageCraftItem(26215, 64, CreativeTabs.tabMisc, 1, "itemQuartzMageCraft");
   public final static Item itemTopazMageCraft = new MageCraftItem(26216, 64, CreativeTabs.tabMisc, 1, "itemTopazMageCraft");
   public final static Item itemAmethystMageCraft = new MageCraftItem(26217, 64, CreativeTabs.tabMisc, 1, "itemAmethystMageCraft");
   public final static Item itemGarnetMageCraft = new MageCraftItem(26218, 64, CreativeTabs.tabMisc, 1, "itemGarnetMageCraft");
   public final static Item itemPotashMageCraft = new MageCraftItem(26219, 64, CreativeTabs.tabMisc, 1, "itemPotashMageCraft");
   public final static Item itemSulphurPowderMageCraft = new MageCraftItem(26220, 64, CreativeTabs.tabMisc, 1, "itemSulphurPowderMageCraft");
   public final static Item itemPhosphateMageCraft = new MageCraftItem(26221, 64, CreativeTabs.tabMisc, 1, "itemPhosphateMageCraft");
   public final static Item itemNetherPowderMageCraft = new MageCraftItem(26222, 64, CreativeTabs.tabMisc, 1, "itemNetherPowderMageCraft");
   public final static Item itemQuicklimeMageCraft = new MageCraftItem(26223, 64, CreativeTabs.tabMisc, 1, "itemQuicklimeMageCraft");
   public final static Item itemVitriolMageCraft = (new MageCraftItem(26224, 1, CreativeTabs.tabMisc, 1, "itemVitriolMageCraft").setContainerItem(Item.glassBottle));
   public final static Item itemPhosphoricAcidMageCraft = new MageCraftItem(26225, 1, CreativeTabs.tabMisc, 1, "itemPhosphoricAcidMageCraft");
   public final static Item itemBrimstoneMageCraft = new MageCraftItem(26226, 64, CreativeTabs.tabMisc, 1, "itemBrimstoneMageCraft");
   public final static Item itemMortarPestleMageCraft = (new MageCraftItem(26227, 1, CreativeTabs.tabMisc, 1, "itemMortarPestleMageCraft").setContainerItem(MageCraft.itemMortarPestleMageCraft));
   public final static Item itemGreekFireMageCraft = new MageCraftItem(26228, 8, CreativeTabs.tabMisc, 1, "itemGreekFireMageCraft");
   public final static Item itemPrismMageCraft = new MageCraftItem(26229, 64, CreativeTabs.tabMisc, 1, "itemPrismMageCraft");
   public final static Item itemBlankScrollMageCraft = new MageCraftItem(26230, 64, CreativeTabs.tabMisc, 1, "itemBlankScrollMageCraft");
   public final static Item itemScrollMageCraft = new MageCraftItem(26231, 1, CreativeTabs.tabMisc, 1, "itemScrollMageCraft");
   public final static Item itemFocusMageCraft = new MageCraftItem(26232, 1, CreativeTabs.tabMisc, 1, "itemFocusMageCraft");
   public final static Item itemPhilospherStoneMageCraft = new MageCraftItem(26233, 1, CreativeTabs.tabMisc, 1, "itemPhilosopherStone");
   public final static Item itemCharlatanWandMageCraft = new MageCraftItem(26234, 1, CreativeTabs.tabMisc, 1, "itemCharlatanWandMageCraft");
   public final static Item itemScryingMirrorMageCraft = new MageCraftItem(26235, 1, CreativeTabs.tabMisc, 1, "itemScryingMirrorMageCraft");
   public final static Item itemExcaliburMageCraft = new MageCraftItem(26236, 1, CreativeTabs.tabMisc, 1, "itemExcaliburMageCraft");
   public final static Item itemMjolnirMageCraft = new MageCraftItem(26237, 1, CreativeTabs.tabMisc, 1, "itemMjolnirMageCraft");
   public final static Item itemMagicUrnMageCraft = new MageCraftItem(26238, 1, CreativeTabs.tabMisc, 1, "itemMagicUrnMageCraft");
   public final static Item itemCrystalManaMageCraft = new MageCraftItem(26239, 16, CreativeTabs.tabMisc, 1, "itemCrystalManaMageCraft");
   public final static Item itemMageJournalMageCraft = new MageCraftItem(26240, 1, CreativeTabs.tabMisc, 1, "itemMageJournalMageCraft");
   public final static Item itemManaCrystal1MageCraft = new MageCraftItem(26241, 1, CreativeTabs.tabMisc, 1, "itemManaCrystal1MageCraft");
   public final static Item itemManaCrystal2MageCraft = new MageCraftItem(26242, 1, CreativeTabs.tabMisc, 1, "itemManaCrystal2MageCraft");
   public final static Item itemManaCrystal3MageCraft = new MageCraftItem(26243, 1, CreativeTabs.tabMisc, 1, "itemManaCrystal3MageCraft");
   public final static Block blockLeadOreMageCraft = new MageCraftBlock(2621, 1, Material.rock, CreativeTabs.tabBlock, "blockLeadOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockSilverOreMageCraft = new MageCraftBlock(2622, 1, Material.rock, CreativeTabs.tabBlock, "blockSilverOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockOnyxOreMageCraft = new MageCraftOnyxOreBlock(2623, 1, Material.rock, CreativeTabs.tabBlock, "blockOnyxOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockRubyOreMageCraft = new MageCraftRubyOreBlock(2624, 1, Material.rock, CreativeTabs.tabBlock, "blockRubyOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockSapphireOreMageCraft = new MageCraftSapphireOreBlock(2625, 1, Material.rock, CreativeTabs.tabBlock, "blockSapphireOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockQuartzOreMageCraft = new MageCraftQuartzOreBlock(2626, 1, Material.rock, CreativeTabs.tabBlock, "blockQuartzOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockTopazOreMageCraft = new MageCraftTopazOreBlock(2627, 1, Material.rock, CreativeTabs.tabBlock, "blockTopazOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockAmethystOreMageCraft = new MageCraftAmethystOreBlock(2628, 1, Material.rock, CreativeTabs.tabBlock, "blockAmethystOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockGarnetOreMageCraft = new MageCraftGarnetOreBlock(2629, 1, Material.rock, CreativeTabs.tabMisc, "blockGarnetOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockSaltpeterOreMageCraft = new MageCraftSaltpeterOreBlock(2630, 1, Material.rock, CreativeTabs.tabBlock, "blockSaltpeterOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockApatiteOreMageCraft = new MageCraftApatiteOreBlock(2631, 1, Material.rock, CreativeTabs.tabBlock, "blockApatiteOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockSulphurOreMageCraft = new MageCraftSulphurOreBlock(2632, 1, Material.rock, CreativeTabs.tabBlock, "blockSulphurOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockLimestoneOreMageCraft = new MageCraftBlock(2633, 1, Material.rock, CreativeTabs.tabBlock, "blockLimestoneOreMageCraft") .setHardness(3F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockAlchemistWorktableMageCraft = new MageCraftBlock(2634, 1, Material.wood, CreativeTabs.tabBlock, "blockAlchemistWorktableMageCraft") .setHardness(2.5F).setStepSound(Block.soundWoodFootstep);
   public final static Block blockWritingDeskMageCraft = new MageCraftBlock(2635, 1, Material.wood, CreativeTabs.tabBlock, "blockWritingDeskMageCraft") .setHardness(2.5F).setStepSound(Block.soundWoodFootstep);
   public final static Block blockArcaneInfuserMageCraft = new MageCraftBlock(2636, 1, Material.rock, CreativeTabs.tabBlock, "blockArcaneInfuserMageCraft") .setHardness(3.5F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockSteamInfuserMageCraft = new MageCraftBlock(2637, 1, Material.rock, CreativeTabs.tabBlock, "blockSteamInfuserMageCraft") .setHardness(3.5F).setStepSound(Block.soundStoneFootstep);
   public final static Block blockGreekFireMageCraft = new MageCraftBlock(2638, 1, Material.glass, CreativeTabs.tabBlock, "blockGreekFireMageCraft") .setHardness(0.3F).setStepSound(Block.soundGlassFootstep);

   @Instance("MageCraftCore")
   public static MageCraft instance;
   
   @SidedProxy(clientSide="greenwolf13.magecraft.client.ClientProxy", serverSide="greenwolf13.magecraft.CommonProxy")
   public static CommonProxy proxy;
   
   @PreInit
   public void preInit(FMLPreInitializationEvent event) {
   }
   
   @Init
   public void load(FMLInitializationEvent event) {
      GameRegistry.addShapelessRecipe(new ItemStack(itemPotashMageCraft, 1), new ItemStack(itemMortarPestleMageCraft), new ItemStack(itemSaltpeterMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemSulphurPowderMageCraft, 1), new ItemStack(itemMortarPestleMageCraft), new ItemStack(itemSulphurMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemPhosphateMageCraft, 1), new ItemStack(itemMortarPestleMageCraft), new ItemStack(itemApatiteMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemNetherPowderMageCraft, 1), new ItemStack(itemMortarPestleMageCraft), new ItemStack(Block.netherrack));
      GameRegistry.addShapelessRecipe(new ItemStack(itemVitriolMageCraft, 1), new ItemStack(itemPotashMageCraft), new ItemStack(itemSulphurPowderMageCraft), new ItemStack(Item.potion));
      GameRegistry.addShapelessRecipe(new ItemStack(itemPhosphoricAcidMageCraft, 1), new ItemStack(itemPhosphateMageCraft), new ItemStack(Item.potion));
      GameRegistry.addShapelessRecipe(new ItemStack(itemBrimstoneMageCraft, 1), new ItemStack(itemSulphurPowderMageCraft), new ItemStack(itemPhosphateMageCraft), new ItemStack(itemNetherPowderMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemMortarPestleMageCraft, 1), new ItemStack(Item.stick), new ItemStack(Item.bowlEmpty));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 1), new ItemStack(itemVitriolMageCraft), new ItemStack(Item.ingotIron));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 1), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(Item.ingotIron));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 1), new ItemStack(itemVitriolMageCraft), new ItemStack(Item.coal), new ItemStack(Item.coal));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 1), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(Item.coal), new ItemStack(Item.coal));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 2), new ItemStack(itemVitriolMageCraft), new ItemStack(itemLeadIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 2), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(itemLeadIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 3), new ItemStack(itemVitriolMageCraft), new ItemStack(itemSilverIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 3), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(itemSilverIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 4), new ItemStack(itemVitriolMageCraft), new ItemStack(itemElectrumIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 4), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(itemElectrumIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 5), new ItemStack(itemVitriolMageCraft), new ItemStack(Item.ingotGold));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 5), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(Item.ingotGold));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 6), new ItemStack(itemVitriolMageCraft), new ItemStack(itemMithrilIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 6), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(itemMithrilIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 7), new ItemStack(itemVitriolMageCraft), new ItemStack(itemAdamantIngotMageCraft));
      GameRegistry.addShapelessRecipe(new ItemStack(itemEssenceMageCraft, 7), new ItemStack(itemPhosphoricAcidMageCraft), new ItemStack(itemAdamantIngotMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.ingotIron, 1), "x  ", "   ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(itemLeadIngotMageCraft, 1), "xx ", "   ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(itemSilverIngotMageCraft, 1), "xxx", "   ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(itemElectrumIngotMageCraft, 1), "xxx", "x  ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.ingotGold, 1), "xxx", "xx ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(itemMithrilIngotMageCraft, 1), "xxx", "xxx", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(itemAdamantIngotMageCraft, 1), "xxx", "xxx", "x  ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.diamond, 1), "xxx", "xxx", "xxx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.coal, 2), "   ", "   ", "  x", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.emerald, 1), "xxx", "xxx", "xx ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(itemRubyMageCraft, 1), "xxx", "xxx", "x x", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(MageCraft.itemSapphireMageCraft, 1), "xxx", "xxx", " xx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(itemQuartzMageCraft, 1), "xxx", "xx ", "xxx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.enderPearl, 1), "xxx", "x x", "xxx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.appleGold, 1), "xxx", " xx", "xxx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.goldenCarrot, 1), "xx ", "xxx", "xxx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.bucketLava, 1), "x x", "xxx", "xxx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.mycelium, 1), " xx", "xxx", "xxx", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.netherrack, 32), " x ", "   ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.stoneBrick, 32), "  x", "   ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.sand, 16), "   ", "x  ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.gravel, 16), "   ", " x ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.wood, 8), "   ", "  x", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.cobblestoneMossy, 1), "   ", "   ", "x  ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Block.slowSand, 16), "   ", "   ", " x ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.lightStoneDust, 1), "x x", "   ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.addRecipe(new ItemStack(Item.diamond, 1), "x  ", "x  ", "   ", 'x', new ItemStack(itemEssenceMageCraft));
      GameRegistry.registerBlock(blockLeadOreMageCraft);
      GameRegistry.registerBlock(blockSilverOreMageCraft);
      GameRegistry.registerBlock(blockOnyxOreMageCraft);
      GameRegistry.registerBlock(blockRubyOreMageCraft);
      GameRegistry.registerBlock(blockSapphireOreMageCraft);
      GameRegistry.registerBlock(blockQuartzOreMageCraft);
      GameRegistry.registerBlock(blockTopazOreMageCraft);
      GameRegistry.registerBlock(blockAmethystOreMageCraft);
      //GameRegistry.registerBlock(blockGarnetMageCraft);
      GameRegistry.registerBlock(blockSaltpeterOreMageCraft);
      GameRegistry.registerBlock(blockApatiteOreMageCraft);
      GameRegistry.registerBlock(blockSulphurOreMageCraft);
      GameRegistry.registerBlock(blockLimestoneOreMageCraft);
      GameRegistry.registerBlock(blockAlchemistWorktableMageCraft);
      GameRegistry.registerBlock(blockWritingDeskMageCraft);
      GameRegistry.registerBlock(blockArcaneInfuserMageCraft);
      //GameRegistry.registerBlock(blockHeatInfuserMageCraft);
      GameRegistry.registerBlock(blockGreekFireMageCraft);
      MinecraftForge.setBlockHarvestLevel(blockLeadOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockSilverOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockOnyxOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockRubyOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockSapphireOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockQuartzOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockTopazOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockAmethystOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockGarnetOreMageCraft, "pickaxe", 2);
      MinecraftForge.setBlockHarvestLevel(blockSaltpeterOreMageCraft, "pickaxe", 0);
      MinecraftForge.setBlockHarvestLevel(blockApatiteOreMageCraft, "pickaxe", 0);
      MinecraftForge.setBlockHarvestLevel(blockSulphurOreMageCraft, "pickaxe", 0);
      MinecraftForge.setBlockHarvestLevel(blockLimestoneOreMageCraft, "pickaxe", 0);
      LanguageRegistry.addName(blockLeadOreMageCraft, "Lead Ore");
      LanguageRegistry.addName(blockSilverOreMageCraft, "Silver Ore");
      LanguageRegistry.addName(blockOnyxOreMageCraft, "Onyx Ore");
      LanguageRegistry.addName(blockRubyOreMageCraft, "Ruby Ore");
      LanguageRegistry.addName(blockSapphireOreMageCraft, "Sapphire Ore");
      LanguageRegistry.addName(blockQuartzOreMageCraft, "Quartz Ore");
      LanguageRegistry.addName(blockTopazOreMageCraft, "Topaz Ore");
      LanguageRegistry.addName(blockAmethystOreMageCraft, "Amethyst Ore");
      LanguageRegistry.addName(blockGarnetOreMageCraft, "Garnet Ore");
      LanguageRegistry.addName(blockSaltpeterOreMageCraft, "Saltpeter Crystal");
      LanguageRegistry.addName(blockApatiteOreMageCraft, "Apatite Crystal");
      LanguageRegistry.addName(blockSulphurOreMageCraft, "Sulphur Crystal");
      LanguageRegistry.addName(blockLimestoneOreMageCraft, "Limestone");
      //LanguageRegistry.addName(blockAlchemistWorktableMageCraft, "Alchemist Worktable");
      LanguageRegistry.addName(blockWritingDeskMageCraft, "Writing Desk");
      LanguageRegistry.addName(blockArcaneInfuserMageCraft, "Arcane Infuser");
      //LanguageRegistry.addName(blockHeatInfuserMageCraft, "Thermionic Infuser");
      LanguageRegistry.addName(blockGreekFireMageCraft, "Greek Fire");
      LanguageRegistry.addName(itemEssenceMageCraft, "Low Essence");
      LanguageRegistry.addName(itemEssence2MageCraft, "Medium Essence");
      LanguageRegistry.addName(itemEssence3MageCraft, "High Essence");
      LanguageRegistry.addName(itemLeadIngotMageCraft, "Lead Ingot");
      LanguageRegistry.addName(itemSilverIngotMageCraft, "Silver Ingot");
      LanguageRegistry.addName(itemMithrilIngotMageCraft, "Mithril Ingot");
      LanguageRegistry.addName(itemAdamantIngotMageCraft, "Adamant Ingot");
      LanguageRegistry.addName(itemElectrumIngotMageCraft, "Electrum Ingot");
      LanguageRegistry.addName(itemSaltpeterMageCraft, "Saltpeter");
      LanguageRegistry.addName(itemSulphurMageCraft, "Sulphur");
      LanguageRegistry.addName(itemApatiteMageCraft, "Apatite");
      LanguageRegistry.addName(itemOnyxMageCraft, "Onyx");
      LanguageRegistry.addName(itemRubyMageCraft, "Ruby");
      LanguageRegistry.addName(itemSapphireMageCraft, "Sapphire");
      LanguageRegistry.addName(itemQuartzMageCraft, "Quartz");
      LanguageRegistry.addName(itemTopazMageCraft, "Topaz");
      LanguageRegistry.addName(itemAmethystMageCraft, "Amethyst");
      LanguageRegistry.addName(itemGarnetMageCraft, "Garnet");
      LanguageRegistry.addName(itemPotashMageCraft, "Nitrate of Potash");
      LanguageRegistry.addName(itemSulphurPowderMageCraft, "Sulphur Powder");
      LanguageRegistry.addName(itemPhosphateMageCraft, "Phosphate");
      LanguageRegistry.addName(itemNetherPowderMageCraft, "Nether Powder");
      LanguageRegistry.addName(itemQuicklimeMageCraft, "Quicklime");
      LanguageRegistry.addName(itemVitriolMageCraft, "Oil of Vitriol");
      LanguageRegistry.addName(itemPhosphoricAcidMageCraft, "Phosphoric Acid");
      LanguageRegistry.addName(itemBrimstoneMageCraft, "Brimstone");
      LanguageRegistry.addName(itemMortarPestleMageCraft, "Mortar and Pestle");
      LanguageRegistry.addName(itemGreekFireMageCraft, "Greek Fire");
      LanguageRegistry.addName(itemPrismMageCraft, "Prism");
      LanguageRegistry.addName(itemBlankScrollMageCraft, "Blank Scroll");
      LanguageRegistry.addName(itemScrollMageCraft, "Scroll");
      LanguageRegistry.addName(itemFocusMageCraft, "Focus");
      LanguageRegistry.addName(itemPhilospherStoneMageCraft, "Philosopher's Stone");
      LanguageRegistry.addName(itemCharlatanWandMageCraft, "Charlatan's Wand");
      LanguageRegistry.addName(itemScryingMirrorMageCraft, "Dr. John Dee's Scrying Mirror");
      LanguageRegistry.addName(itemExcaliburMageCraft, "Excalibur");
      LanguageRegistry.addName(itemMjolnirMageCraft, "Mjolnir");
      LanguageRegistry.addName(itemMagicUrnMageCraft, "Magic Urn");
      LanguageRegistry.addName(itemCrystalManaMageCraft, "Crystalized Mana Star");
      LanguageRegistry.addName(itemMageJournalMageCraft, "Mage Journal");
      LanguageRegistry.addName(itemManaCrystal1MageCraft, "Low Mana Crystal");
      LanguageRegistry.addName(itemManaCrystal2MageCraft, "Medium Mana Crystal");
      LanguageRegistry.addName(itemManaCrystal3MageCraft, "High Mana Crystal");
      proxy.registerRenderers();
      GameRegistry.registerWorldGenerator(new WorldgeneratorMageCraft());
	  System.out.println("MageCraft ready!");
   }
   
   @PostInit
   public void postInit(FMLPostInitializationEvent event) {
   }
}